[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"

[dependencies]
wrapper = { path = "wrapper" }
ease = { git = "https://github.com/jrhea/ease", branch = "engine" }